<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="Jayarees-MacBook-Pro.local" name="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice" tests="7" failures="1" timestamp="27 Nov 2019 16:32:27 GMT" time="75.154" errors="0">
  <testcase name="i_am_a_user_of_Axate_and_I_am_on_the_registration_page_through_popbitch_FUN" time="5.559" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice"/>
  <testcase name="i_register_successfully_on_popbitch_with_one_pound" time="30.384" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice"/>
  <testcase name="click_ok_on_the_finish_notice" time="2.065" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice"/>
  <testcase name="navigate_to_a_premium_article_on_newbury" time="4.685" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice"/>
  <testcase name="opt_just_charge_me_on_the_newpublication_notice_and_click_ok" time="20.156" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice"/>
  <testcase name="wallet_balance_is_detucted_by_twentyp" time="6.183" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice"/>
  <testcase name="free_point_is_detucted_by_twentyp" time="6.122" classname="Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice">
    <failure type="java.lang.AssertionError" message="expected [Frees] but found [Free]">
      <![CDATA[java.lang.AssertionError: expected [Frees] but found [Free]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice.free_point_is_detucted_by_twentyp(NEWSMO19_Transaction_from_new_publication_notice.java:158)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- free_point_is_detucted_by_twentyp -->
</testsuite> <!-- Stepdef.Newburylive.NEWSMO19_Transaction_from_new_publication_notice -->
